# .github/workflows/build.yml
# Автоматическая компиляция мода БЕЗ установки локальных программ (CMake, VS Code, C++)
# Просто залейте файлы на ваш GitHub репозиторий, и GitHub Actions сам соберет готовый .geode файл!

name: Build Geode Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest
          target: win
        - name: Android 32-bit
          os: ubuntu-latest
          target: android32
        - name: Android 64-bit
          os: ubuntu-latest
          target: android64

    name: Build (${{ matrix.config.name }})
    runs-on: ${{ matrix.config.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Mod
      uses: geode-sdk/build-geode-mod@v3
      with:
        target: ${{ matrix.config.target }}
